version: 0.2

phases:
  install:
    commands:
      - echo building Thread Access Info...
      - wget https://services.gradle.org/distributions/gradle-7.1.1-bin.zip
      - unzip -d /opt/gradle gradle-7.1.1-bin.zip
      - export PATH=$PATH:/opt/gradle/gradle-7.1.1/bin
      - gradle -version
    on-failure: ABORT
  pre_build:
    commands:
      - echo build startet at `date`
    on-failure: ABORT
  build:
    commands:
      - gradle build
      - gradle test
    on-failure: ABORT
  post_build:
    commands:
      - echo finished at `date`
    on-failure: ABORT

artifacts:
  files:
    - build/distributions/thread-access-plugin-${PLUGIN_VERSION}.jar